language: node_js

node_js:
  - "4"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
 - npm install -g gulp

script: gulp

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: payform-dev.beanstream.com
  local-dir: build
  skip_cleanup: true
  region: us-west-2
  detect_encoding: true
  cache_control: "public, max-age=0"
  on:
    branch: dev
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: payform-test.beanstream.com
  local-dir: build
  skip_cleanup: true
  region: us-west-2
  detect_encoding: true
  cache_control: "public, max-age=0"
  on:
    branch: test
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: payform-master.beanstream.com
  local-dir: build
  skip_cleanup: true
  region: us-west-2
  detect_encoding: true
  cache_control: "public, max-age=0"
  on:
    branch: master
