language: node_js

node_js:
  - v4.2.1

before_script:
 - npm install -g gulp

script: gulp

branches:
  only:
  - master
  - test

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: payform.beanstream.com
  local-dir: build
  skip_cleanup: true
  region: us-west-2
  detect_encoding: true
  cache_control: "public, max-age=0"
  on:
    branch: master
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: payform-test.beanstream.com
  local-dir: build
  skip_cleanup: true
  region: us-west-2
  detect_encoding: true
  cache_control: "public, max-age=0"
  on:
    branch: test
